//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileDistributor.Logger.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileDistributor.Logger.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create directory &quot;{0}&quot;.
        /// </summary>
        public static string CannotCreateDirectory {
            get {
                return ResourceManager.GetString("CannotCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find destination directory &quot;{0}&quot;.
        /// </summary>
        public static string CannotFindDestinationDirectory {
            get {
                return ResourceManager.GetString("CannotFindDestinationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration file.
        /// </summary>
        public static string ConfigurationFileError {
            get {
                return ResourceManager.GetString("ConfigurationFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination directory &quot;{0}&quot; was created.
        /// </summary>
        public static string DestinationDirectoryWasCreated {
            get {
                return ResourceManager.GetString("DestinationDirectoryWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string ErrorLevel {
            get {
                return ResourceManager.GetString("ErrorLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; was created.
        /// </summary>
        public static string FileCreated {
            get {
                return ResourceManager.GetString("FileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t move file &quot;{0}&quot;, because it&apos;s currently use by other process.
        /// </summary>
        public static string FileIsCurrentlyInUse {
            get {
                return ResourceManager.GetString("FileIsCurrentlyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t move file &quot;{0}&quot;, because it was deleted.
        /// </summary>
        public static string FileWasDeletedBeforTransfering {
            get {
                return ResourceManager.GetString("FileWasDeletedBeforTransfering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; was moved successfully.
        /// </summary>
        public static string FileWasMovedSuccessfully {
            get {
                return ResourceManager.GetString("FileWasMovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; will move to default directory &quot;{1}&quot;.
        /// </summary>
        public static string FileWillMoveToDefaultDirectory {
            get {
                return ResourceManager.GetString("FileWillMoveToDefaultDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; will move to directory &quot;{1}&quot;.
        /// </summary>
        public static string FileWillMoveUsingExistingRule {
            get {
                return ResourceManager.GetString("FileWillMoveUsingExistingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        public static string InfoLevel {
            get {
                return ResourceManager.GetString("InfoLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start watching.
        /// </summary>
        public static string StartWatching {
            get {
                return ResourceManager.GetString("StartWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop watching.
        /// </summary>
        public static string StopWatching {
            get {
                return ResourceManager.GetString("StopWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error with file &quot;{0}&quot;.
        /// </summary>
        public static string UnexpectedErrorWithFile {
            get {
                return ResourceManager.GetString("UnexpectedErrorWithFile", resourceCulture);
            }
        }
    }
}
